### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by keithcallenberg** [usr42/ttrss-sendtokindle#1]
After installing the plugin as instructed with Tiny Tiny RSS v1.15.3, I receive the following error:

"Error sending email: Could not instantiate mail function"

Are there any php or apache modules that need to be enabled for this plugin to function properly?

Thanks!

**Comment by usr42** [comment]
This seems to be a problem with the mail function of php.
How does the [mail function] section in your php.ini looks like? 
Is there an error message in your mail log(something like /var/log/maillog), when you try to send the article to your kindle?
Is there a working sendmail or something equivalent installed at your system?
It the mail function blocked by the disable_functions parameter in the php.ini?

**Comment by usr42** [comment]
This seems to be a problem with the mail function of php. It should be no problem with the plugin.
Can you send mails from php with other ttrss plugins or other php software at your server?
How does the [mail function] section in your php.ini looks like? 
Is there an error message in your mail log (something like /var/log/maillog) when you try to send an article to your kindle?
Do you have a working sendmail or something equivalent installed?
Maybe the mail function is disabled in your php.ini(disable_functions)?
